database:
  url: ""
  username: "root"
  password: "root"

login:
  attempts: 5

messages:
  already-registered: "<white>You are already registered!"
  already-logged: "<white>You are already logged in!"
  not-registered: "<white>You are not registered yet. Please use <dark_purple>/register [password]</dark_purple>"
  not-logged: "<white>You are not logged in yet. Please use <dark_purple>/login [password]</dark_purple>"
  insufficient-characters: "<white>Please use a minimum of <dark_purple>4 characters</dark_purple>"
  wrong-credentials: "<white>You entered the wrong password. Please try again!"

  register:
    usage: "<dark_purple><bold>AUTH</bold></dark_purple> <dark_gray><bold>:: </bold></dark_gray> <white>Register - <dark_purple>/register [password]</dark_purple>"
    success: "<green>You have successfully registered!"

  login:
    usage: "<dark_purple><bold>AUTH</bold></dark_purple> <dark_gray><bold>:: </bold></dark_gray> <white>Login - <dark_purple>/login [password]</dark_purple>"
    success: "<green>You have successfully logged in!"

  logout:
    usage: "<dark_purple><bold>AUTH</bold></dark_purple> <dark_gray><bold>:: </bold></dark_gray> <white>Logout - <dark_purple>/logout</dark_purple>"
    kick-screen: "<red>You have been logged out by own choice. \nPlease reconnect the server if it was made by the mistake."

  changepass:
    usage: "<dark_purple><bold>AUTH</bold></dark_purple> <dark_gray><bold>:: </bold></dark_gray> <white>Change password - <dark_purple>/changepass [old password] [new password]</dark_purple>"
    kick-screen: "<green>Your password has been changed successfully. \n\n<white>Please rejoin the server and log in using your new password."